### ISSUE TITLE
SR motor error

### ISSUE THREAD

**Issue by harshasunder-1** [Eomys/pyleecan#248]
Hi,

Im a new user to this library. 
I have more familiarity with the SRM motor than the PMSM so I thought ill try to build a simple 6-4 motor to understand how to use the library. I used the Lamslot object  to build the rotor since it doesnt need a magnet or winding, and a LamslotWind  object for the stator. I also used your tutorial and set the simulation object.
However when i ran the simulation.run() command, I found that it bombed with the error 
" 'LamSlot' object has no attribute 'comp_angle_d_axis' "
Is the Lam Slot object the correct choice for the rotor?
From my understanding of the code in the LamSlotMag Class this function for the SR motor needs to just return the angle from the x-axis to the centre of the first rotor tooth in the clockwise direction, which in this cases is just 0. Is this correct?

The library looks amazing and Im really excited to see how it will grow. Really loved the simplicity of defining the shape once you get the hang of it. 

thank you 
harsha

![Capture](https://user-images.githubusercontent.com/10281763/99882566-68f32f00-2c47-11eb-9aa6-64b3c4338bcf.PNG)

**Comment by EmileDvs** [comment]
Hello Harsha,

Thanks for the feedback and for investigating the implementation of SRM motor. Indeed the LamSlot class is the most suitable to SRM rotor lamination. 

The simulation crashes because when it runs MagFEMM model it asks for rotor initial positions, which asks both stator and rotor laminations their d_axis angle, so that MagFEMM sets the proper rotor position in FEMM that achieves the requested Id/Iq. However, the d-axis is not defined for a generic LamSlot lamination, because this axis is related to laminations with windings or magnets. 

Hence for me the problem is more that the method which asks for rotor initial position is not generic enough to account for other laminations that those having dq-axes. As a quick fix you can do as you said: call comp_angle_d_axis method if the lamination has this method, otherwise set it to 0.

Furthermore, a cleaner way to proceed would be to properly define the SRM rotor initial position, something like "rotor (un)aligned  position" at t=0s, which then sets up stator currents and rotor position accordingly. I don't know how to exactly implement it in pyleecan and it also depends on your need so we should talk about this all together before starting implementing this further approach.

Best regards,
Emile
