### ISSUE TITLE
Problem regarding installing pyleecan

### ISSUE THREAD

**Issue by Ksp-3086** [Eomys/pyleecan#421]
Hi,
I am installing pyleecan for the first time. I already have installed python 3.6 and microsoft visual studio as an IDE. On the site it says to type the command " pip install pyleecan". I opened the shell for python and typed the command there, it did not work. I am not that well versed in programming so is there something I am missing or doing wrong?

**Comment by SebGue** [comment]
Hello KSP,

you got to run that command in your OS shell. Maybe you need administrativ rights for it to complete.

Best regards, Sebastian

**Comment by Ksp-3086** [comment]
Hello @SebGue ,
I opened up command prompt on my windows and tried to run it under the administrative username. Do I need to go into a specific directory where pip or python is installed?

**Comment by SebGue** [comment]
You can run it from wherever you like.

**Comment by Ksp-3086** [comment]
I got an error like this in the image when I ran it in the command prompt.
![pyleecan](https://user-images.githubusercontent.com/84498303/131496296-a8e982ed-c96d-4a42-9d65-e99f4632f079.png)
It says pip is not recognized as an external command or an operable  program or batch file.

**Comment by SebGue** [comment]
Okay, then you got to go to the pip install directory, since the python path seems not to be in your environment variables.

**Comment by Ksp-3086** [comment]
![pyleecan](https://user-images.githubusercontent.com/84498303/131541161-36eec739-6748-4b65-afb9-7d4c94ead7f9.png)
Yup, it still did not work

**Comment by SebGue** [comment]
If you go to the dir where pip is located, it should work. But i can't tell you where that is, right now.

**Comment by Ksp-3086** [comment]
![python](https://user-images.githubusercontent.com/84498303/131549070-d8a2a582-a4b7-47b3-bf38-56d064bf922f.png)
it shows python not installed and neither is pip. For pyleecan it was recommended to use from 3.6 to 3.8 so I chose 3.6 . I have it installed as you can see in the picture but I do not know why is cmd showing like this. Any ideas

**Comment by SebGue** [comment]
I think thats because your python path is not in the path environment variable. 
You have to find your python installation directory (where the python.exe is loacted). In my case it is 'C:\Users\SebGue\AppData\Local\Programs\Python\Python38\'. There is also a 'Scripts' folder with the pip.exe
You may add that two directories to your path variable.

But my proposal would be to uninstall python and install 3.8 instead. Also make sure you use the x64 version. While the installation you have the possibility to add the path to the environment variable. So you should check this option.
Then you will be able to run python and pip from any path in the cmd.

Hope this will finally help to solve your problem.

BR, Sebastian

**Comment by Ksp-3086** [comment]
Thanks for the help. Its working with python 3.8 without even going to the directory. The reason why 3.6 was not working was as it uses different commands or maybe the support is withdrawn already.

**Comment by SebGue** [comment]
You are welcome. So can we close this issue?
