### ISSUE TITLE
importerror: c:\users\kashi\appdata\roaming\python\python38\shiboken2\libshiboken does not exist while using anaconda for pyleecan

### ISSUE THREAD

**Issue by Ksp-3086** [Eomys/pyleecan#426]
I tried running pyleecan with anaconda but I was unable to do so due to this error.

**Comment by BonneelP** [comment]
Hello,

Sorry for answering just now, I'm back from holiday. Did you managed to run pyleecan in anaconda at the end ? 
If I remember well a colleague had a similar error. I see that your python is installed in "c:\users\kashi\appdata" so maybe you are using windows and you have installed python through windows tools? Or are you using the python included in Anaconda? Python and its packages can be magic (https://xkcd.com/353/) but it can also be hard to install/configure in particular if you have several python on your computer.

We are going to rewrite the "how to install pyleecan" page according to our latest experiments (I hope this week). If you don't manage to run pyleecan Anaconda by then it should help (otherwise we can continue discussing here). 

But maybe this issue is outdated. I saw in issue #427 that you are also using VScode. Do you need to have both VScode and Anaconda? Personally I have the following setup: only one python installed from the website (https://www.python.org/downloads/) and VScode (I find Anaconda a bit too rigid when handling packages but some of my colleagues use it everyday). For Jupyter notebook related work, I use directly the dedicated interface from jupyter. 

Best regards,
Pierre

**Comment by Ksp-3086** [comment]
I was not able to run anaconda so I uninstalled anaconda and all the python versions installed. Then I only installed vs code and it is working fine. I am able to run jupyter notebooks in that too, so now I am able to work without much of the problems.

**Comment by BonneelP** [comment]
As it was an installation problem I think that we can close this issue. Feel free to reopen it if you need further help.
Best regards,
Pierre
